# syntax=docker/dockerfile:1

ARG VERSION

FROM rust:slim
ARG VERSION

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    pkg-config \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install schematools-cli@${VERSION}

ENTRYPOINT ["schematools-cli"]
CMD ["--help"]
