on:
  pull_request: {}
  push:
    branches:
      - master

name: build

jobs:
  build:
    name: Build for ${{ matrix.config.short }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            short: linux-amd64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            short: linux-arm64
          - os: macos-26-intel
            target: x86_64-apple-darwin
            short: darwin-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            short: windows-amd64
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
            short: windows-arm64
          - os: macos-latest
            target: aarch64-apple-darwin
            short: darwin-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}
      - run: cargo build --release --target ${{ matrix.config.target }}
